name: Deploy to LWS via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [sanity_webhook, sanity-webhook]

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupération du code (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 3. Installation des dépendances
        run: npm ci

      - name: 4. Build de l'application Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: "a9cb5294"
          NEXT_PUBLIC_SANITY_DATASET: "production"
          NEXT_PUBLIC_SANITY_API_VERSION: "2024-01-01"

      - name: 5. Déploiement vers LWS via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftp.isamkinshasa.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          # On déploie le dossier généré par le build statique
          local-dir: ./out/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
